### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by rlee1990** [zegoim/zego-express-flutter-sdk#11]
Is the host able to mute other participants audio and video?

**Comment by patrick-fu** [comment]
Refer to this [document](https://doc-zh.zego.im/faq/set_audience)
(Sorry that this document is not currently available in english)

**Comment by Match-Yang** [comment]
1. The host can use [sendCustomCommand](https://pub.dev/documentation/zego_express_engine/latest/zego_express_engine/ZegoExpressEngineIM/sendCustomCommand.html) to send a command to the participants
2. Then the participants will received the command over the [onIMRecvCustomCommand](https://pub.dev/documentation/zego_express_engine/latest/zego_express_engine/ZegoExpressEngine/onIMRecvCustomCommand.html) callback
3. Then the participants can disable his/her audio with the [muteMicrophone](https://pub.dev/documentation/zego_express_engine/latest/zego_express_engine/ZegoExpressEngineDevice/muteMicrophone.html) method and disable his/her video with the [enableCamera](https://pub.dev/documentation/zego_express_engine/latest/zego_express_engine/ZegoExpressEngineDevice/enableCamera.html) method

**Comment by Match-Yang** [comment]
> Is the host able to mute other participants audio and video?

Please feel free to join our Discord channel to ask any questions: https://discord.com/invite/EtNRATttyp

**Comment by rlee1990** [comment]
Thanks
