### ISSUE TITLE
Flutter 运行Android环境报错

### ISSUE THREAD

**Issue by Rafong973** [zegoim/zego-express-flutter-sdk#12]
更新了flutter package以后，就报错了。
请问如何解决？

报错内容：
<img width="1606" alt="image" src="https://user-images.githubusercontent.com/22493242/221460829-acb1e9da-376a-4c9a-938e-452bd9361585.png">

**Comment by Z-ErQi** [comment]
我们这边上传到jitpack上面的Android aar包被吞了，建议更新到最新的3.2.1版本。
3.2.0版本后我们这边使用的是私有的maven仓库了，不会再出现这种吞包现象
