### ISSUE TITLE
getting these errors:

### ISSUE THREAD

**Issue by fisforfaheem** [zegoim/zego-express-flutter-sdk#13]
Note: /Users/4edoc/.pub-cache/hosted/pub.dev/flutter_ringtone_player-3.2.0/android/src/main/java/io/inway/ringtone/player/FlutterRingtonePlayerPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/4edoc/.pub-cache/hosted/pub.dev/zego_express_engine-3.2.1/android/src/main/java/im/zego/zego_express_engine/internal/ZegoExpressEngineMethodHandler.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
../../.pub-cache/hosted/pub.dev/flutter_screenutil_zego-5.6.0/lib/src/screen_util.dart:58:5: Error: Type 'FlutterWindow' not found.
    FlutterWindow? window,
    ^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.dev/flutter_screenutil_zego-5.6.0/lib/src/screen_util.dart:58:5: Error: 'FlutterWindow' isn't a type.
    FlutterWindow? window,
    ^^^^^^^^^^^^^
Target kernel_snapshot failed: Exception

FAILURE: Build failed with an exception.

* Where:
Script '/Users/4edoc/Downloads/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 1159

* What went wrong:

**Comment by Z-ErQi** [comment]
flutter_screenutil_zego was forked to address specific issues with the original flutter_screenutil package. Please continue using the original flutter_screenutil. Additionally, note that flutter_screenutil_zego will soon be deprecated. Refer to https://pub.dev/packages/flutter_screenutil for more information.

**Comment by fisforfaheem** [comment]
But i am using zego package only, please somehow fix it, flutter won't let
us build apps, we are paying customer
