### ISSUE TITLE
sdk内部拉流质量状态一直报一个类型错误

### ISSUE THREAD

**Issue by KangLeon** [zegoim/zego-express-flutter-sdk#3]
I/flutter (26785): error:type 'int' is not a subtype of type 'ZegoVideoCodecID';stack:#0      new ZegoPlayStreamQuality.fromMap (package:zego_express_engine/src/zego_express_defines.dart:1166:5)
I/flutter (26785): #1      ZegoExpressImpl._eventListener (package:zego_express_engine/src/zego_express_impl.dart:905:33)
I/flutter (26785): #2      _rootRunUnary (dart:async/zone.dart:1198:47)
I/flutter (26785): #3      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
I/flutter (26785): #4      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
I/flutter (26785): #5      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
I/flutter (26785): #6      _DelayedData.perform (dart:async/stream_impl.dart:611:14)
I/flutter (26785): #7      _StreamImplEvents.handleNext (dart:async/stream_impl.dart:730:11)
I/flutter (26785): #8      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:687:7)
I/flutter (26785): #9      _rootRun (dart:async/zone.dart:1182:47)
I/flutter (26785): #10     _CustomZone.run (dart:async/zone.dart:1093:19)
I/flutter (26785): #11     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
I/flutter (26785): #12     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)

**Comment by patrick-fu** [comment]
👍 Thanks for the feedback, this issue has been fixed in version 1.19.1
