### ISSUE TITLE
添加依赖后，项目运行不起来

### ISSUE THREAD

**Issue by XiaoAnXA** [zegoim/zego-express-flutter-sdk#4]
我创建了一个新项目，添加依赖后运行不起来，移除依赖后项目可以运行起来了

卡在了：Running Gradle task 'assembleDebug'...这里就不动了

 flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.4, on Linux, locale zh_CN.UTF-8)
 
[✓] Android toolchain - develop for Android devices (Android SDK version
    30.0.0-rc4)
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.51.1)
[✓] Connected device (1 available)

• No issues found!

**Comment by patrick-fu** [comment]
Since this Flutter SDK plugin needs to rely on the native SDK, it needs to be downloaded from JCenter on Android. Please check if you can access JCenter normally, or try to use mirror source.
