### ISSUE TITLE
No implementation found for method loginRoom

### ISSUE THREAD

**Issue by aikd101** [zegoim/zego-express-flutter-sdk#5]
![Screen Shot 2021-01-12 at 11 42 20 AM](https://user-images.githubusercontent.com/57030712/104266795-51a82380-54cb-11eb-81c8-8eb11f57d8c3.png)

**Comment by patrick-fu** [comment]
Please paste the output of running `flutter run -v` and `flutter doctor -v` here

**Comment by aikd101** [comment]
its alright now..I made a mistake i entered the wrong AppSign (The authentication key of the project)

**Comment by Sherlock2547** [comment]
try call ZegoExpressWrapper.createEngineWithProfile
